### ISSUE TITLE
这个只能在win32下打包吗

### ISSUE THREAD

**Issue by fxk01** [dungang/lucky-lottery#1]
在win64下打包怎么修改配置啊

**Comment by dungang** [comment]
命令说明： 
* location of project：项目所在路径 
* name of project：打包的项目名字 
* platform：确定了你要构建哪个平台的应用（Windows、Mac 还是 Linux） 
* architecture：决定了使用 x86 还是 x64 还是两个架构都用 
* electron version：electron-prebuilt 的版本 
* optional options：可选选项

**Comment by dungang** [comment]
查看 package.json文件的script ，默认是x64的

**Comment by tryandcatch** [comment]
`package.json`文件的`script`语句中的`package`改为下面的就好了（要确定`--electron-version`否则报`Unable to determine Electron version. Please specify an Electron version`的错）：

`"package": "electron-packager ./ lucky-lottery --platform=win32  --out ../lucky-lottery-release --electron-version=1.4.13 --overwrite --icon=./images/app.icns"`

**Comment by dungang** [comment]
@tryandcatch good！我检查了一下，再当时更新脚本的时候，在--electron-version=1.4.13的等号可能不误删了，现在重新提交

**Comment by dungang** [comment]
@seagulljohnson 来取最新代码 在运行
