### ISSUE TITLE
Can't init successed.

### ISSUE THREAD

**Issue by sparkwong3** [dungang/lucky-lottery#2]
Hi I can't do the right operation while follow your steps.

**Comment by dungang** [comment]
I have updated latest electron ,you can try again

**Comment by ayangshaw** [comment]
通過 npm start 啟動之後 ,一直卡在 開始抽獎的畫面上，運行環境（vs2017+node.js+npm）
通過鍵盤alt + n 沒反應，不過ctrl + Q可以退出，也可以調試。but can't work~

**Comment by dungang** [comment]
@sparkwong3 [啟動之後沒反應 #3](https://github.com/dungang/lucky-lottery/issues/2)
